
export const KEY_METADATA: Record<string, { label: string; category: string }> = {
    // Color Section
    'Color.Background': { label: '背景', category: '外観' },
    'Color.WindowBorder': { label: 'ウィンドウ境界線', category: '外観' },
    'Color.WindowSeparator': { label: 'ウィンドウ区切り', category: '外観' },
    'Color.Footer': { label: 'フッター背景', category: '外観' },
    'Color.FooterProgress': { label: 'フッター進捗バー', category: '外観' },
    'Color.Grouping': { label: 'グループ背景', category: '外観' },
    'Color.GroupingHover': { label: 'グループ (ホバー)', category: '外観' },
    'Color.GroupingSelect': { label: 'グループ (選択)', category: '外観' },
    'Color.TitleHeader': { label: 'タイトルヘッダー', category: '外観' },
    'Color.BorderSelect': { label: '境界線 (選択)', category: '外観' },
    'Color.Border': { label: '境界線', category: '外観' },
    'Color.BorderFocus': { label: '境界線 (フォーカス)', category: '外観' },
    'Color.Text': { label: 'テキスト (基本)', category: 'フォント' },
    'Color.TextDisable': { label: 'テキスト (無効)', category: 'フォント' },
    'Color.TextSelect': { label: 'テキスト (選択)', category: 'フォント' },
    'Color.ButtonBody': { label: 'ボタン', category: '外観' },
    'Color.ButtonBodyHover': { label: 'ボタン (ホバー)', category: '外観' },
    'Color.ButtonBodyPress': { label: 'ボタン (プレス)', category: '外観' },
    'Color.ButtonBodyDisable': { label: 'ボタン (無効)', category: '外観' },
    'Color.ButtonBodySelect': { label: 'ボタン (選択)', category: '外観' },
    'Color.SliderCursor': { label: 'スライダーカーソル', category: '外観' },
    'Color.TrackBarRange': { label: 'トラックバー範囲', category: '外観' },
    'Color.ZoomGauge': { label: 'ズームゲージ', category: '外観' },
    'Color.ZoomGaugeHover': { label: 'ズームゲージ (ホバー)', category: '外観' },
    'Color.ZoomGaugeOff': { label: 'ズームゲージ (オフ)', category: '外観' },
    'Color.ZoomGaugeOffHover': { label: 'ズームゲージ (オフ、ホバー)', category: '外観' },
    'Color.FrameCursor': { label: 'フレームカーソル', category: '外観' },
    'Color.FrameCursorWide': { label: 'フレームカーソル (幅広)', category: '外観' },
    'Color.PlayerCursor': { label: '再生カーソル (タイムライン)', category: '外観' },
    'Color.GuideLine': { label: 'ガイドライン', category: '外観' },
    'Color.Layer': { label: 'レイヤー背景', category: '外観' },
    'Color.LayerHeader': { label: 'レイヤーヘッダー', category: '外観' },
    'Color.LayerHover': { label: 'レイヤー (ホバー)', category: '外観' },
    'Color.LayerDisable': { label: 'レイヤー (無効)', category: '外観' },
    'Color.LayerRange': { label: 'レイヤー範囲', category: '外観' },
    'Color.LayerRangeFrame': { label: 'レイヤー範囲フレーム', category: '外観' },
    'Color.ObjectVideo': { label: '映像オブジェクト', category: '外観' },
    'Color.ObjectVideoSelect': { label: '映像オブジェクト (選択)', category: '外観' },
    'Color.ObjectAudio': { label: '音声オブジェクト', category: '外観' },
    'Color.ObjectAudioSelect': { label: '音声オブジェクト (選択)', category: '外観' },
    'Color.ObjectControl': { label: '制御オブジェクト', category: '外観' },
    'Color.ObjectControlSelect': { label: '制御オブジェクト (選択)', category: '外観' },
    'Color.ObjectVideoFilter': { label: '映像フィルタオブジェクト', category: '外観' },
    'Color.ObjectVideoFilterSelect': { label: '映像フィルタオブジェクト (選択)', category: '外観' },
    'Color.ObjectAudioFilter': { label: '音声フィルタオブジェクト', category: '外観' },
    'Color.ObjectAudioFilterSelect': { label: '音声フィルタオブジェクト (選択)', category: '外観' },
    'Color.ObjectHover': { label: 'オブジェクト (ホバー)', category: '外観' },
    'Color.ObjectFocus': { label: 'オブジェクト境界線 (フォーカス)', category: '外観' },
    'Color.ObjectSection': { label: 'オブジェクト中間点', category: '外観' },
    'Color.Anchor': { label: 'アンカー', category: '外観' },
    'Color.AnchorHover': { label: 'アンカー (ホバー)', category: '外観' },
    'Color.AnchorEdge': { label: 'アンカー縁', category: '外観' },
    
    // Font Section
    'Font.DefaultFamily': { label: 'デフォルトフォントファミリー', category: 'フォント' },
    'Font.Control': { label: 'コントロールフォント', category: 'フォント' },
    'Font.EditControl': { label: '編集コントロールフォント', category: 'フォント' },
    'Font.PreviewTime': { label: 'プレビュー時間フォント', category: 'フォント' },
    'Font.LayerObject': { label: 'レイヤー/オブジェクトフォント', category: 'フォント' },
    'Font.TimeGauge': { label: 'タイムゲージフォント', category: 'フォント' },
    'Font.Footer': { label: 'フッターフォント', category: 'フォント' },
    'Font.TextEdit': { label: 'テキスト編集フォント', category: 'フォント' },
    'Font.Log': { label: 'ログフォント', category: 'フォント' },
    
    // Layout Section
    'Layout.WindowSeparatorSize': { label: 'ウィンドウ区切りサイズ', category: 'サイズと間隔' },
    'Layout.ScrollBarSize': { label: 'スクロールバーサイズ', category: 'サイズと間隔' },
    'Layout.FooterHeight': { label: 'フッターの高さ', category: 'サイズと間隔' },
    'Layout.TitleHeaderHeight': { label: 'タイトルヘッダーの高さ', category: 'サイズと間隔' },
    'Layout.TimeGaugeHeight': { label: 'タイムゲージの高さ', category: 'サイズと間隔' },
    'Layout.LayerHeight': { label: 'レイヤーの高さ', category: 'サイズと間隔' },
    'Layout.LayerHeaderWidth': { label: 'レイヤーヘッダーの幅', category: 'サイズと間隔' },
    'Layout.SettingItemHeaderWidth': { label: '設定項目ヘッダーの幅', category: 'サイズと間隔' },
    'Layout.SettingItemHeight': { label: '設定項目の高さ', category: 'サイズと間隔' },
    'Layout.SettingItemMarginWidth': { label: '設定項目のマージン', category: 'サイズと間隔' },
    'Layout.SettingHeaderHeight': { label: '設定ヘッダーの高さ', category: 'サイズと間隔' },
    'Layout.ExplorerWindowNum': { label: 'エクスプローラウィンドウの数', category: 'サイズと間隔' },

    // Format Section
    'Format.FooterLeft': { label: 'フッター書式 (左)', category: 'その他' },
    'Format.FooterRight': { label: 'フッター書式 (右)', category: 'その他' },
};
